### ISSUE TITLE
One issue when run your code

### ISSUE THREAD

**Issue by hsvgbkhgbv** [IC3Net/IC3Net#1]
Hi, 

When I run your code there happens an error attached below, please see it.

<img width="731" alt="screenshot 2019-01-26 at 10 50 36" src="https://user-images.githubusercontent.com/16505330/51786137-55183800-2158-11e9-9e7c-abc92a131480.png">

**Comment by apsdehal** [comment]
Hey, which version of Pytorch you are using?

**Comment by hsvgbkhgbv** [comment]
Thank you for your reply. I have updated the pytorch verison to the latest 1.0 and the code can work now.

**Comment by apsdehal** [comment]
Thanks. Closing the issue then. Reopen if any issue persists.
