### ISSUE TITLE
Display trained models

### ISSUE THREAD

**Issue by nikajerkovic** [IC3Net/IC3Net#22]
Is it possible to display, for example, predator-prey after training and record a video? I saw information about the display(during training) flag, but I am interested in the results after training.

**Comment by nikajerkovic** [comment]
I am actually interested in rendering as in paper:

![image](https://github.com/IC3Net/IC3Net/assets/62607974/d728dd76-e538-4763-8a4e-b7d901adf280)

**Comment by tshrjn** [comment]
@nikajerkovic Hi there, these rendering where hand-created in tikz for representation purposes. We've much simpler visualization via ncurses in the env package.
